export interface FamilyMember {
  id: string;
  fullName: string;
  photo?: string;
  gender?: "Male" | "Female" | "Other";
  generation?: string;
  birthday?: string;
  anniversary?: string;
  address?: string;
  mapsLink?: string;
  city?: string;
  country?: string;
  nativePlace?: string;
  phone?: string;
  whatsapp?: string;
  email?: string;
  personalWebsite?: string;
  linkedIn?: string;
  instagram?: string;
  profession?: string;
  company?: string;
  previousCompany?: string;
  businessName?: string;
  education?: string;
  bloodGroup?: string;
  mainFamilyBranch?: string;
  subFamilyBranch?: string;
  spouseName?: string;
  childrenNames?: string[];
  hobbies?: string;
  skills?: string;
  languagesSpoken?: string;
  emergencyContact?: string;
  notes?: string;
  addedAt?: string;
  fatherId?: string;
  motherId?: string;
  spouseId?: string;
  generationNumber?: number;
  siblingOrder?: number;
  lineageRootId?: string;
}

export const SAMPLE_MEMBERS: FamilyMember[] = [
  // === GENERATION 1 === Root Ancestor
  {
    id: "gk",
    fullName: "Gandalal Keshav Shah",
    gender: "Male",
    generationNumber: 1,
    generation: "1st Generation",
    city: "Rajkot",
    country: "India",
    nativePlace: "Rajkot",
    profession: "Businessman",
    mainFamilyBranch: "G K Shah Family",
    spouseName: "Savitaben Shah",
    spouseId: "gk-wife",
    childrenNames: ["Ramesh Shah", "Suresh Shah", "Mahesh Shah", "Dinesh Shah", "Vilas Shah", "Ashok Shah", "Lata Mehta", "Rekha Joshi"],
    notes: "Founder and patriarch of the G K Shah family",
    siblingOrder: 0,
    addedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "gk-wife",
    fullName: "Savitaben Shah",
    gender: "Female",
    generationNumber: 1,
    generation: "1st Generation",
    city: "Rajkot",
    country: "India",
    nativePlace: "Rajkot",
    profession: "Homemaker",
    mainFamilyBranch: "G K Shah Family",
    spouseName: "Gandalal Keshav Shah",
    spouseId: "gk",
    siblingOrder: 0,
    addedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // === GENERATION 2 === Sons and daughters of GK Shah
  {
    id: "1",
    fullName: "Ramesh Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ramesh",
    gender: "Male",
    generationNumber: 2,
    generation: "2nd Generation",
    nativePlace: "Rajkot",
    birthday: "1945-05-12",
    anniversary: "1968-12-05",
    city: "Mumbai",
    country: "India",
    phone: "+91 9876543210",
    whatsapp: "+91 9876543210",
    email: "ramesh.shah@example.com",
    profession: "Retired",
    bloodGroup: "O+",
    mainFamilyBranch: "Mumbai Branch",
    subFamilyBranch: "Ramesh Line",
    spouseName: "Sita Shah",
    spouseId: "2",
    fatherId: "gk",
    motherId: "gk-wife",
    childrenNames: ["Rajesh Shah", "Pooja Mehta"],
    siblingOrder: 1,
    addedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    fullName: "Sita Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sita",
    gender: "Female",
    generationNumber: 2,
    generation: "2nd Generation",
    nativePlace: "Rajkot",
    birthday: "1948-08-22",
    anniversary: "1968-12-05",
    city: "Mumbai",
    country: "India",
    phone: "+91 9876543211",
    whatsapp: "+91 9876543211",
    profession: "Homemaker",
    bloodGroup: "A+",
    mainFamilyBranch: "Mumbai Branch",
    subFamilyBranch: "Ramesh Line",
    spouseName: "Ramesh Shah",
    spouseId: "1",
    childrenNames: ["Rajesh Shah", "Pooja Mehta"],
    addedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "son2",
    fullName: "Suresh Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Suresh",
    gender: "Male",
    generationNumber: 2,
    generation: "2nd Generation",
    birthday: "1948-03-10",
    city: "Surat",
    country: "India",
    phone: "+91 9876543220",
    profession: "Textile Merchant",
    bloodGroup: "B+",
    mainFamilyBranch: "Surat Branch",
    subFamilyBranch: "Suresh Line",
    spouseName: "Kamla Shah",
    spouseId: "son2-wife",
    fatherId: "gk",
    motherId: "gk-wife",
    childrenNames: ["Amit Shah"],
    siblingOrder: 2,
    addedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "son2-wife",
    fullName: "Kamla Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kamla",
    gender: "Female",
    generationNumber: 2,
    generation: "2nd Generation",
    birthday: "1950-07-20",
    city: "Surat",
    country: "India",
    profession: "Homemaker",
    bloodGroup: "O+",
    mainFamilyBranch: "Surat Branch",
    subFamilyBranch: "Suresh Line",
    spouseName: "Suresh Shah",
    spouseId: "son2",
    childrenNames: ["Amit Shah"],
    addedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "son3",
    fullName: "Mahesh Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mahesh",
    gender: "Male",
    generationNumber: 2,
    generation: "2nd Generation",
    birthday: "1950-09-05",
    city: "Ahmedabad",
    country: "India",
    phone: "+91 9876543221",
    profession: "Engineer",
    bloodGroup: "A+",
    mainFamilyBranch: "Ahmedabad Branch",
    subFamilyBranch: "Mahesh Line",
    spouseName: "Usha Shah",
    spouseId: "son3-wife",
    fatherId: "gk",
    motherId: "gk-wife",
    childrenNames: ["Rajesh Shah", "Meena Shah"],
    siblingOrder: 3,
    addedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "son3-wife",
    fullName: "Usha Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Usha",
    gender: "Female",
    generationNumber: 2,
    generation: "2nd Generation",
    birthday: "1952-04-15",
    city: "Ahmedabad",
    country: "India",
    profession: "Teacher",
    bloodGroup: "B-",
    mainFamilyBranch: "Ahmedabad Branch",
    subFamilyBranch: "Mahesh Line",
    spouseName: "Mahesh Shah",
    spouseId: "son3",
    childrenNames: ["Rajesh Shah", "Meena Shah"],
    addedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "son4",
    fullName: "Dinesh Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dinesh",
    gender: "Male",
    generationNumber: 2,
    generation: "2nd Generation",
    birthday: "1953-11-22",
    city: "Pune",
    country: "India",
    phone: "+91 9876543222",
    profession: "Chartered Accountant",
    bloodGroup: "AB+",
    mainFamilyBranch: "Pune Branch",
    subFamilyBranch: "Dinesh Line",
    fatherId: "gk",
    motherId: "gk-wife",
    siblingOrder: 4,
    addedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "son5",
    fullName: "Vilas Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vilas",
    gender: "Male",
    generationNumber: 2,
    generation: "2nd Generation",
    birthday: "1956-06-18",
    city: "Delhi",
    country: "India",
    phone: "+91 9876543223",
    profession: "Government Officer",
    bloodGroup: "O-",
    mainFamilyBranch: "Delhi Branch",
    subFamilyBranch: "Vilas Line",
    fatherId: "gk",
    motherId: "gk-wife",
    siblingOrder: 5,
    addedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "son6",
    fullName: "Ashok Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ashok",
    gender: "Male",
    generationNumber: 2,
    generation: "2nd Generation",
    birthday: "1959-01-30",
    city: "Baroda",
    country: "India",
    phone: "+91 9876543224",
    profession: "Pharmacist",
    bloodGroup: "A-",
    mainFamilyBranch: "Baroda Branch",
    subFamilyBranch: "Ashok Line",
    fatherId: "gk",
    motherId: "gk-wife",
    siblingOrder: 6,
    addedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "dau1",
    fullName: "Lata Mehta",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lata",
    gender: "Female",
    generationNumber: 2,
    generation: "2nd Generation",
    birthday: "1961-08-12",
    city: "Mumbai",
    country: "India",
    profession: "Homemaker",
    bloodGroup: "B+",
    mainFamilyBranch: "Mumbai Branch",
    subFamilyBranch: "Lata Line",
    fatherId: "gk",
    motherId: "gk-wife",
    siblingOrder: 7,
    addedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "dau2",
    fullName: "Rekha Joshi",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rekha",
    gender: "Female",
    generationNumber: 2,
    generation: "2nd Generation",
    birthday: "1963-03-25",
    city: "Jaipur",
    country: "India",
    profession: "Doctor",
    bloodGroup: "O+",
    mainFamilyBranch: "Jaipur Branch",
    subFamilyBranch: "Rekha Line",
    fatherId: "gk",
    motherId: "gk-wife",
    siblingOrder: 8,
    addedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // === GENERATION 3 === Grandchildren of GK Shah
  {
    id: "3",
    fullName: "Rajesh Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh",
    gender: "Male",
    generationNumber: 3,
    generation: "3rd Generation",
    nativePlace: "Mumbai",
    birthday: "1972-03-15",
    anniversary: "1998-02-14",
    city: "Ahmedabad",
    country: "India",
    phone: "+91 9876543212",
    whatsapp: "+91 9876543212",
    email: "rajesh.shah@example.com",
    profession: "Business Owner",
    company: "Shah Enterprises",
    bloodGroup: "B+",
    mainFamilyBranch: "Ahmedabad Branch",
    subFamilyBranch: "Ramesh Line",
    spouseName: "Meena Shah",
    spouseId: "5",
    fatherId: "son3",
    motherId: "son3-wife",
    childrenNames: ["Ravi Shah", "Sneha Shah"],
    siblingOrder: 1,
    addedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    fullName: "Pooja Mehta",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pooja",
    gender: "Female",
    generationNumber: 3,
    generation: "3rd Generation",
    birthday: "1975-11-08",
    anniversary: "2001-05-20",
    city: "London",
    country: "UK",
    phone: "+44 7700 900000",
    whatsapp: "+44 7700 900000",
    email: "pooja.mehta@example.com",
    profession: "Architect",
    bloodGroup: "O+",
    mainFamilyBranch: "London Branch",
    subFamilyBranch: "Ramesh Line",
    fatherId: "1",
    motherId: "2",
    siblingOrder: 2,
    addedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    fullName: "Meena Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Meena",
    gender: "Female",
    generationNumber: 3,
    generation: "3rd Generation",
    birthday: "1974-07-30",
    anniversary: "1998-02-14",
    city: "Ahmedabad",
    country: "India",
    profession: "Teacher",
    bloodGroup: "A-",
    mainFamilyBranch: "Ahmedabad Branch",
    spouseName: "Rajesh Shah",
    spouseId: "3",
    childrenNames: ["Ravi Shah", "Sneha Shah"],
    addedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "8",
    fullName: "Amit Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amit",
    gender: "Male",
    generationNumber: 3,
    generation: "3rd Generation",
    birthday: "1980-02-25",
    city: "Mumbai",
    country: "India",
    profession: "Doctor",
    bloodGroup: "AB+",
    mainFamilyBranch: "Surat Branch",
    subFamilyBranch: "Suresh Line",
    fatherId: "son2",
    motherId: "son2-wife",
    siblingOrder: 1,
    addedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // === GENERATION 4 === Great-grandchildren
  {
    id: "6",
    fullName: "Ravi Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ravi",
    gender: "Male",
    generationNumber: 4,
    generation: "4th Generation",
    birthday: "2000-09-10",
    city: "New York",
    country: "USA",
    phone: "+1 212 555 1234",
    email: "ravi.shah@example.com",
    profession: "Software Engineer",
    company: "Tech Corp",
    bloodGroup: "B+",
    mainFamilyBranch: "Ahmedabad Branch",
    fatherId: "3",
    motherId: "5",
    siblingOrder: 1,
    addedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "7",
    fullName: "Sneha Shah",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha",
    gender: "Female",
    generationNumber: 4,
    generation: "4th Generation",
    birthday: "2004-12-05",
    city: "Ahmedabad",
    country: "India",
    profession: "Student",
    bloodGroup: "O+",
    mainFamilyBranch: "Ahmedabad Branch",
    fatherId: "3",
    motherId: "5",
    siblingOrder: 2,
    addedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
